%YAML 1.2
---
name: Dockerfile
file_extensions:
  - Dockerfile
scope: source.dockerfile
contexts:
  main:
    - include: comments
    - match: '^(\s*)(?i:(FROM|RUN|CMD|LABEL|EXPOSE|ENV|ADD|COPY|ENTRYPOINT|VOLUME|USER|WORKDIR|ARG|ONBUILD|STOPSIGNAL|HEALTHCHECK|SHELL))\b'
      captures:
        2: keyword.control.directive.dockerfile
      push:
        - meta_scope: meta.instruction.dockerfile
        - match: '$'
          pop: true
        - include: strings
    - include: strings

  comments:
    - match: '#.*$'
      scope: comment.line.number-sign.dockerfile

  strings:
    - match: '"'
      scope: punctuation.definition.string.begin.dockerfile
      push:
        - meta_scope: string.quoted.double.dockerfile
        - match: '"'
          scope: punctuation.definition.string.end.dockerfile
          pop: true
        - match: '\\.'
          scope: constant.character.escape.dockerfile
    - match: "'"
      scope: punctuation.definition.string.begin.dockerfile
      push:
        - meta_scope: string.quoted.single.dockerfile
        - match: "'"
          scope: punctuation.definition.string.end.dockerfile
          pop: true
