PackageIdentifier: OpenAI.Codex
PackageVersion: {{VERSION}}
PackageLocale: en-US
Publisher: OpenAI
PublisherUrl: https://github.com/openai
PublisherSupportUrl: https://github.com/openai/codex/issues
PrivacyUrl: https://openai.com/policies/privacy-policy
PackageName: Codex
PackageUrl: https://github.com/openai/codex
License: Proprietary
ShortDescription: Native Codex CLI (Rust) for terminal and TUI workflows.
Moniker: codex
Tags:
  - codex
  - cli
  - ai
  - agent
ManifestType: defaultLocale
ManifestVersion: 1.5.0
